# Generated by Django 3.2 on 2022-10-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersRole',
        ),
    ]
