# Generated by Django 3.2 on 2022-10-31 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20221031_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于非菜单权限需要选择一个可以成为菜单的权限', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='rbac.permission', verbose_name='关联的权限'),
        ),
    ]
