# Generated by Django 3.2 on 2022-11-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20221101_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='menu',
            new_name='menu_id',
        ),
    ]
