# Generated by Django 3.2 on 2022-11-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_rename_menu_permission_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
